### ISSUE TITLE
Unknown error if the client is not authorized to connect

### ISSUE THREAD

**Issue by btry** [sskaje/mqtt#14]
Hi

If CONNACK contains 0x00 0x05 the spec says it means **Connection Refused, not authorized**

If this happens, the code returns **ERROR  Connection failed! (Error: 0x00 0x05|Unknown error)**

**Comment by sskaje** [comment]
Hi @btry , is #11 what you mean?
It should have been fixed for months.

**Comment by btry** [comment]
Hi

My copy is outdated. Sorry for the inconvenience.
