### ISSUE TITLE
Header Timestamp always 1970-01-01T01:00:00+01:00

### ISSUE THREAD

**Issue by rcaboni** [sskaje/mqtt#25]
Hi,
   I tried your beautiful library and work fine, but all messages have the Timestamp not set and the ActiveMQ report Header Timestamp 1970-01-01T01:00:00+01:00.
   Is there a way to set the Timestamp from library or it's a bug ?
Thanks
Roberto

**Comment by sskaje** [comment]
I didn't see a TIMESTAMP field in MQTT 3.1.1 protocol.

Maybe you need to see how ActiveMQ implements this Timestamp header.

sskaje@gmail.com
https://sskaje.me/

**Comment by rcaboni** [comment]
Correct sskaje,
    the MQTT protocol haven't Timestamp. Now I think MQTT timestamp is for other protocols its supported.
Thanks
