### ISSUE TITLE
last update on packagist.org is 2018-03-16

### ISSUE THREAD

**Issue by badmansan** [sskaje/mqtt#31]
So, when running ```composer require sskaje/mqtt dev-master``` it install version in commit [38cf01a](https://github.com/sskaje/mqtt/commit/38cf01a177ed8e6ff387cdefcf11ba42594e330f) from the 16 Mar 2018. The latest pull requests is not included.

**Comment by sskaje** [comment]
I forgot to add a webhook for this repository, I'll push an empty update to force trigger

**Comment by badmansan** [comment]
Thank's, now it update to last commit
