### ISSUE TITLE
MQTT 3.1.1

### ISSUE THREAD

**Issue by sskaje** [sskaje/mqtt#4]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

**Comment by w3yyb** [comment]
https://github.com/w3yyb/MQTT-CN/blob/master/mqtt-v3.1.1-os.md  中文版

**Comment by sskaje** [comment]
You may see it pushed in two or three weeks.

**Comment by w3yyb** [comment]
同一消息的PUBACK, PUBREC, PUBREL messageid一致，客户端必须通过msgid确定qos1, qos2消息。 这个 php客户端id处理可能有错误，只保留了last message ID，应该保存未响应的sub、unsub、qos1、qos2 publish。

**Comment by w3yyb** [comment]
ok, very good, but  have a problem ,unsubscribe not work

**Comment by sskaje** [comment]
@w3yyb new issue with more details ?

**Comment by w3yyb** [comment]
protected function do_unsubscribe() {
        # set msg id
        $msgid = mt_rand(1, 65535);
        # send SUBSCRIBE
        $unsubscribeobj = $this->getMessageObject(CrystalPushMessageType::UNSUBSCRIBE);
        $unsubscribeobj->setMsgID($msgid);

        foreach ($this->topics_to_unsubscribe as $tn=>$topic_name) {
            if (!isset($this->topics[$topic_name])) {
                # log
               // continue;    //  cancel this line  unsubscribe will work good 去掉这行就行了 
            }

**Comment by w3yyb** [comment]
黑黑,这是要更新了吗
