### ISSUE TITLE
do_publish is public : is it wanted ?

### ISSUE THREAD

**Issue by dethegeek** [sskaje/mqtt#8]
Hi

I'm beginning to replace a MQTT library lacking QoS. It seems promising; thank you very much.

I noticed the methods do_subscribe() and do_unsubscribe() are protected, whereas do_publish() is public.

I wanted to point it out as I believe is is maybe intended to be protected too.

**Comment by sskaje** [comment]
I guess i may have missed it. 
do_publish was set public while I was trying to write some test scripts before publish_sync/async. 

2.0 is still not stable. If you don't mind, I'll let do_publish stay public and this issue open for some time.

Thank you.

sskaje

**Comment by dethegeek** [comment]
I close this for you. Thanks !
